#!/usr/bin/env bash
# Redirection
sed -i '/server_name _;/a \\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
/etc/init.d/nginx reload
