#!/usr/bin/env bash
# Setup a load balancer
sudo apt -y update
apt install -y haproxy
echo "frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server 2257-web-01 35.231.197.40:80 check
   server 2257-web-02 35.237.198.52:80 check" >> /etc/haproxy/haproxy.cfg
systemctl restart haproxy
