#!/usr/bin/env bash
#prints current process pid

touch /var/run/holbertonscript.pid

trap "echo 'I hate the kill command' ; rm /var/run/holbertonscript.pid" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/holbertonscript.pid" SIGQUIT

while :
do
    echo "To infinity and beyond"
    sleep 2
done
