#!/usr/bin/env bash
#Prints Holberton School 10 times with a while
i=1

while [ $i -le 20 ]
do
    echo "$i"
    if [[ $i -eq 4 ]]
    then
        echo "bad luck from China"
    elif [[ $i -eq 9 ]]
    then
        echo "good luck from Japan"
    elif [[ $i -eq 17 ]]
    then
        echo "good luck from Italy"
    fi
    ((i++))
done
