#!/usr/bin/env bash
#Prints Holberton School 10 times with a while
i=0

while [ $i -le 12 ]
do
    echo "Hour: $i"
    j=1
    while [ $j -lt 60 ]
    do
        echo "$j"
        ((j++))
    done
    ((i++))
done
