#!/usr/bin/env bash
#Change localhost and facebook's ip
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '/127.0.1.1/a8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
